#!/usr/bin/python3

"""
    Test cases for BaseModels class
"""

import unittest
from models.base_model import BaseModel
from io import StringIO
import sys
import datetime


class TestBase(unittest.TestCase):
    """
        BaseModels class test
    """

    def setUp(self):
        """
            Setting up instances
        """
        self.my_model = BaseModel()
        self.my_model.name = "Raj Molaah"

    def TearDown(self):
        """
            Deleting an instance.
        """
        del self.my_model

    def test_id_type(self):
        """
            confirm id is in string format
        """
        self.assertEqual("<class 'str'>", str(type(self.my_model.id)))

    def test_ids_differ(self):
        """
            Verifies if the IDs of two instances vary from one another
        """
        new_model = BaseModel()
        self.assertNotEqual(new_model.id, self.my_model.id)

    def test_name(self):
        """
            Confirms if an attribute is added
        """
        self.assertEqual("Raj Molaah", self.my_model.name)

    def test_a_updated_created_equal(self):
        """
            Verify if the two dates are the same
        """
        self.assertEqual(self.my_model.updated_at.year,
                         self.my_model.created_at.year)

    def test_save(self):
        """
            Verifies that the dates in the updated_at
            property vary after updating the instance.
        """
        old_update = self.my_model.updated_at
        self.my_model.save()
        self.assertNotEqual(self.my_model.updated_at, old_update)

    def test_str_overide(self):
        """
            Confirms the right output is printed
        """
        backup = sys.stdout
        inst_id = self.my_model.id
        capture_out = StringIO()
        sys.stdout = capture_out
        print(self.my_model)

        cap = capture_out.getvalue().split(" ")
        self.assertEqual(cap[0], "[BaseModel]")

        self.assertEqual(cap[1], "({})".format(inst_id))
        sys.stdout = backup

    def test_to_dict_type(self):
        """
            Confirms the to_dict method type that is returned
        """

        self.assertEqual("<class 'dict'>",
                         str(type(self.my_model.to_dict())))

    def test_to_dict_class(self):
        """
            Verifies the existence of the __class__ key.
        """

        self.assertEqual("BaseModel", (self.my_model.to_dict())["__class__"])

    def test_to_dict_type_updated_at(self):
        """
            verifies the updated_at value's type
        """
        self.assertEqual("<class 'str'>",
                         str(type((self.my_model.to_dict())["updated_at"])))

    def test_to_dict_type_created_at(self):
        """
            verifies the created_at value's type
        """
        tmp = self.my_model.to_dict()
        self.assertEqual("<class 'str'>", str(type(tmp["created_at"])))

    def test_kwargs_instantiation(self):
        """
            Make sure that an instance has been
            generated by utilizing the key-value pair
        """
        my_model_dict = self.my_model.to_dict()
        new_model = BaseModel(**my_model_dict)
        self.assertEqual(new_model.id, self.my_model.id)

    def test_type_created_at(self):
        """
            Verify that the data type of the
            updated_at for the new model is datetime
        """
        my_model_dict = self.my_model.to_dict()
        new_model = BaseModel(my_model_dict)
        self.assertTrue(isinstance(new_model.created_at, datetime.datetime))

    def test_type_updated_at(self):
        """
            Verify that the data type of the
            new_model's created_at is datetime.
        """
        my_model_dict = self.my_model.to_dict()
        new_model = BaseModel(my_model_dict)
        self.assertTrue(isinstance(new_model.updated_at, datetime.datetime))

    def test_compare_dict(self):
        """
            Verify that the dictionary values of the
            new_model and my_model are the same
        """
        my_model_dict = self.my_model.to_dict()
        new_model = BaseModel(**my_model_dict)
        new_model_dict = new_model.to_dict()
        self.assertEqual(my_model_dict, new_model_dict)

    def test_instance_diff(self):
        """
            Verify that the instances of my_model
            and new_model are different
        """
        my_model_dict = self.my_model.to_dict()
        new_model = BaseModel(my_model_dict)
        self.assertNotEqual(self.my_model, new_model)
